# Generated by Django 4.1.3 on 2022-11-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koliListeleme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anaSayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='anaSayfa/')),
            ],
        ),
    ]
